// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/evm/bandwidth/v1/bandwidth.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the bandwidth module parameters.
type Params struct {
	// bandwidth_per_share is the amount of atest minted for each submitted share.
	BandwidthPerShare cosmossdk_io_math.Int `protobuf:"bytes,1,opt,name=bandwidth_per_share,json=bandwidthPerShare,proto3,customtype=cosmossdk.io/math.Int" json:"bandwidth_per_share"`
	// daily_topup_amount is minted to a registered device's owner once per day
	// if that owner's spendable balance is zero.
	DailyTopupAmount cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=daily_topup_amount,json=dailyTopupAmount,proto3,customtype=cosmossdk.io/math.Int" json:"daily_topup_amount"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_1db72b9a22b191ac, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

// Device represents a registered ESP32 device on-chain.
type Device struct {
	// device_id uniquely identifies the physical device (e.g. its MAC address).
	DeviceId string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// owner is the wallet address credited with minted bandwidth for this
	// device's shares.
	Owner string `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	// public_key is the device's secp256k1 public key (compressed, 33 bytes),
	// used to verify share submissions signed by the device's private key.
	PublicKey []byte `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// last_nonce is the highest accepted share-submission nonce (replay guard).
	LastNonce uint64 `protobuf:"varint,4,opt,name=last_nonce,json=lastNonce,proto3" json:"last_nonce,omitempty"`
	// last_topup_time is the unix timestamp of the last daily zero-balance
	// top-up paid to this device's owner.
	LastTopupTime int64 `protobuf:"varint,5,opt,name=last_topup_time,json=lastTopupTime,proto3" json:"last_topup_time,omitempty"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}
func (*Device) Descriptor() ([]byte, []int) {
	return fileDescriptor_1db72b9a22b191ac, []int{1}
}
func (m *Device) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Device) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Device.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Device) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Device.Merge(m, src)
}
func (m *Device) XXX_Size() int {
	return m.Size()
}
func (m *Device) XXX_DiscardUnknown() {
	xxx_messageInfo_Device.DiscardUnknown(m)
}

var xxx_messageInfo_Device proto.InternalMessageInfo

func (m *Device) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *Device) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Device) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *Device) GetLastNonce() uint64 {
	if m != nil {
		return m.LastNonce
	}
	return 0
}

func (m *Device) GetLastTopupTime() int64 {
	if m != nil {
		return m.LastTopupTime
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "cosmos.evm.bandwidth.v1.Params")
	proto.RegisterType((*Device)(nil), "cosmos.evm.bandwidth.v1.Device")
}

func init() {
	proto.RegisterFile("cosmos/evm/bandwidth/v1/bandwidth.proto", fileDescriptor_1db72b9a22b191ac)
}

var fileDescriptor_1db72b9a22b191ac = []byte{
	// 392 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xc1, 0xca, 0xd3, 0x40,
	0x10, 0xc7, 0xb3, 0x7e, 0x5f, 0x8b, 0x59, 0x14, 0xed, 0x5a, 0x31, 0x54, 0x9a, 0x86, 0x1c, 0x6c,
	0xe8, 0x21, 0xa1, 0x78, 0xf3, 0xd6, 0xe2, 0xa5, 0x08, 0x52, 0x62, 0x4f, 0x5e, 0xc2, 0x26, 0x59,
	0x9a, 0xa5, 0xdd, 0x6c, 0x48, 0x36, 0xa9, 0x79, 0x05, 0x4f, 0x3e, 0x86, 0xc7, 0xbe, 0x84, 0xd0,
	0x63, 0xf1, 0x24, 0x1e, 0x8a, 0xb4, 0x87, 0xbe, 0x86, 0x64, 0x17, 0xda, 0x5e, 0x94, 0xef, 0x12,
	0x66, 0x7e, 0x33, 0xff, 0xc9, 0xfc, 0x67, 0xe1, 0x30, 0xe2, 0x05, 0xe3, 0x85, 0x47, 0x2a, 0xe6,
	0x85, 0x38, 0x8d, 0x37, 0x34, 0x16, 0x89, 0x57, 0x8d, 0xaf, 0x89, 0x9b, 0xe5, 0x5c, 0x70, 0xf4,
	0x4a, 0x35, 0xba, 0xa4, 0x62, 0xee, 0xb5, 0x56, 0x8d, 0x7b, 0x1d, 0xcc, 0x68, 0xca, 0x3d, 0xf9,
	0x55, 0xbd, 0xbd, 0xee, 0x92, 0x2f, 0xb9, 0x0c, 0xbd, 0x26, 0x52, 0xd4, 0xfe, 0x09, 0x60, 0x7b,
	0x8e, 0x73, 0xcc, 0x0a, 0xe4, 0xc3, 0x17, 0x97, 0x19, 0x41, 0x46, 0xf2, 0xa0, 0x48, 0x70, 0x4e,
	0x0c, 0x60, 0x01, 0x47, 0x9f, 0xda, 0xbb, 0xc3, 0x40, 0xfb, 0x7d, 0x18, 0xbc, 0x54, 0x7f, 0x2c,
	0xe2, 0x95, 0x4b, 0xb9, 0xc7, 0xb0, 0x48, 0xdc, 0x59, 0x2a, 0xbe, 0x9f, 0xb7, 0x23, 0xe0, 0x77,
	0x2e, 0xf2, 0x39, 0xc9, 0x3f, 0x35, 0x62, 0x34, 0x87, 0x28, 0xc6, 0x74, 0x5d, 0x07, 0x82, 0x67,
	0x65, 0x16, 0x60, 0xc6, 0xcb, 0x54, 0x18, 0x8f, 0x1e, 0x3c, 0xf2, 0xb9, 0x54, 0x2f, 0x1a, 0xf1,
	0x44, 0x6a, 0xdf, 0xd9, 0x5f, 0xcf, 0xdb, 0x51, 0xff, 0xe6, 0x40, 0x5f, 0x6e, 0x4e, 0xa4, 0x9c,
	0xd8, 0x3f, 0x00, 0x6c, 0xbf, 0x27, 0x15, 0x8d, 0x08, 0x7a, 0x0d, 0xf5, 0x58, 0x46, 0x01, 0x8d,
	0x95, 0x15, 0xff, 0xb1, 0x02, 0xb3, 0x18, 0x75, 0x61, 0x8b, 0x6f, 0x52, 0x92, 0xab, 0x85, 0x7c,
	0x95, 0xa0, 0x3e, 0x84, 0x59, 0x19, 0xae, 0x69, 0x14, 0xac, 0x48, 0x6d, 0xdc, 0x59, 0xc0, 0x79,
	0xe2, 0xeb, 0x8a, 0x7c, 0x20, 0x75, 0x53, 0x5e, 0xe3, 0x42, 0x04, 0x29, 0x4f, 0x23, 0x62, 0xdc,
	0x5b, 0xc0, 0xb9, 0xf7, 0xf5, 0x86, 0x7c, 0x6c, 0x00, 0x7a, 0x03, 0x9f, 0xc9, 0xb2, 0x32, 0x2c,
	0x28, 0x23, 0x46, 0xcb, 0x02, 0xce, 0x9d, 0xff, 0xb4, 0xc1, 0xd2, 0xc9, 0x82, 0x32, 0xf2, 0x7f,
	0x1f, 0x6a, 0xf9, 0xe9, 0x64, 0x77, 0x34, 0xc1, 0xfe, 0x68, 0x82, 0x3f, 0x47, 0x13, 0x7c, 0x3b,
	0x99, 0xda, 0xfe, 0x64, 0x6a, 0xbf, 0x4e, 0xa6, 0xf6, 0x79, 0xb8, 0xa4, 0x22, 0x29, 0x43, 0x37,
	0xe2, 0xcc, 0xfb, 0xc7, 0x0c, 0x51, 0x67, 0xa4, 0x08, 0xdb, 0xf2, 0x99, 0xdf, 0xfe, 0x1d, 0x00,
	0x48, 0xb7, 0x59, 0x5d, 0x53, 0x02, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.DailyTopupAmount.Size()
		i -= size
		if _, err := m.DailyTopupAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintBandwidth(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.BandwidthPerShare.Size()
		i -= size
		if _, err := m.BandwidthPerShare.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintBandwidth(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *Device) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Device) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Device) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LastTopupTime != 0 {
		i = encodeVarintBandwidth(dAtA, i, uint64(m.LastTopupTime))
		i--
		dAtA[i] = 0x28
	}
	if m.LastNonce != 0 {
		i = encodeVarintBandwidth(dAtA, i, uint64(m.LastNonce))
		i--
		dAtA[i] = 0x20
	}
	if len(m.PublicKey) > 0 {
		i -= len(m.PublicKey)
		copy(dAtA[i:], m.PublicKey)
		i = encodeVarintBandwidth(dAtA, i, uint64(len(m.PublicKey)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintBandwidth(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.DeviceId) > 0 {
		i -= len(m.DeviceId)
		copy(dAtA[i:], m.DeviceId)
		i = encodeVarintBandwidth(dAtA, i, uint64(len(m.DeviceId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintBandwidth(dAtA []byte, offset int, v uint64) int {
	offset -= sovBandwidth(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.BandwidthPerShare.Size()
	n += 1 + l + sovBandwidth(uint64(l))
	l = m.DailyTopupAmount.Size()
	n += 1 + l + sovBandwidth(uint64(l))
	return n
}

func (m *Device) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DeviceId)
	if l > 0 {
		n += 1 + l + sovBandwidth(uint64(l))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovBandwidth(uint64(l))
	}
	l = len(m.PublicKey)
	if l > 0 {
		n += 1 + l + sovBandwidth(uint64(l))
	}
	if m.LastNonce != 0 {
		n += 1 + sovBandwidth(uint64(m.LastNonce))
	}
	if m.LastTopupTime != 0 {
		n += 1 + sovBandwidth(uint64(m.LastTopupTime))
	}
	return n
}

func sovBandwidth(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozBandwidth(x uint64) (n int) {
	return sovBandwidth(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBandwidth
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BandwidthPerShare", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBandwidth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBandwidth
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBandwidth
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BandwidthPerShare.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DailyTopupAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBandwidth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBandwidth
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBandwidth
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DailyTopupAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBandwidth(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBandwidth
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Device) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBandwidth
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Device: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Device: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeviceId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBandwidth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBandwidth
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBandwidth
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DeviceId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBandwidth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBandwidth
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBandwidth
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublicKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBandwidth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthBandwidth
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthBandwidth
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PublicKey = append(m.PublicKey[:0], dAtA[iNdEx:postIndex]...)
			if m.PublicKey == nil {
				m.PublicKey = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastNonce", wireType)
			}
			m.LastNonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBandwidth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastNonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastTopupTime", wireType)
			}
			m.LastTopupTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBandwidth
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastTopupTime |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipBandwidth(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBandwidth
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBandwidth(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBandwidth
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBandwidth
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBandwidth
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthBandwidth
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupBandwidth
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthBandwidth
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthBandwidth        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBandwidth          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupBandwidth = fmt.Errorf("proto: unexpected end of group")
)
