// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/evm/bandwidth/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgRegisterDevice struct {
	Owner     string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	DeviceId  string `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	PublicKey []byte `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// device_signature is a proof-of-possession check (security fix, 8 Sep
	// 2026 chain audit finding #1) - hand-added to this generated file
	// (Docker/buf toolchain unavailable) mirroring PublicKey's pattern
	// exactly, field number 4. See tx.proto / msg_server.go for the full
	// rationale.
	DeviceSignature []byte `protobuf:"bytes,4,opt,name=device_signature,json=deviceSignature,proto3" json:"device_signature,omitempty"`
}

func (m *MsgRegisterDevice) Reset()         { *m = MsgRegisterDevice{} }
func (m *MsgRegisterDevice) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterDevice) ProtoMessage()    {}
func (*MsgRegisterDevice) Descriptor() ([]byte, []int) {
	return fileDescriptor_73caeafae94255fb, []int{0}
}
func (m *MsgRegisterDevice) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterDevice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterDevice.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterDevice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterDevice.Merge(m, src)
}
func (m *MsgRegisterDevice) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterDevice) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterDevice.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterDevice proto.InternalMessageInfo

func (m *MsgRegisterDevice) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *MsgRegisterDevice) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *MsgRegisterDevice) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *MsgRegisterDevice) GetDeviceSignature() []byte {
	if m != nil {
		return m.DeviceSignature
	}
	return nil
}

type MsgRegisterDeviceResponse struct {
}

func (m *MsgRegisterDeviceResponse) Reset()         { *m = MsgRegisterDeviceResponse{} }
func (m *MsgRegisterDeviceResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterDeviceResponse) ProtoMessage()    {}
func (*MsgRegisterDeviceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_73caeafae94255fb, []int{1}
}
func (m *MsgRegisterDeviceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterDeviceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterDeviceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterDeviceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterDeviceResponse.Merge(m, src)
}
func (m *MsgRegisterDeviceResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterDeviceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterDeviceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterDeviceResponse proto.InternalMessageInfo

type MsgSubmitShare struct {
	// relayer signs and pays for this transaction; it does NOT need to be the
	// device's owner and cannot forge shares (see signature below).
	Relayer    string `protobuf:"bytes,1,opt,name=relayer,proto3" json:"relayer,omitempty"`
	DeviceId   string `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	ShareCount uint32 `protobuf:"varint,3,opt,name=share_count,json=shareCount,proto3" json:"share_count,omitempty"`
	Nonce      uint64 `protobuf:"varint,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// signature is the device's ECDSA signature over
	// sha256("{device_id}|{share_count}|{nonce}"), made with the device's own
	// private key (never leaves the device).
	Signature []byte `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *MsgSubmitShare) Reset()         { *m = MsgSubmitShare{} }
func (m *MsgSubmitShare) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitShare) ProtoMessage()    {}
func (*MsgSubmitShare) Descriptor() ([]byte, []int) {
	return fileDescriptor_73caeafae94255fb, []int{2}
}
func (m *MsgSubmitShare) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitShare) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitShare.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitShare) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitShare.Merge(m, src)
}
func (m *MsgSubmitShare) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitShare) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitShare.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitShare proto.InternalMessageInfo

func (m *MsgSubmitShare) GetRelayer() string {
	if m != nil {
		return m.Relayer
	}
	return ""
}

func (m *MsgSubmitShare) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *MsgSubmitShare) GetShareCount() uint32 {
	if m != nil {
		return m.ShareCount
	}
	return 0
}

func (m *MsgSubmitShare) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *MsgSubmitShare) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type MsgSubmitShareResponse struct {
	MintedAmount string `protobuf:"bytes,1,opt,name=minted_amount,json=mintedAmount,proto3" json:"minted_amount,omitempty"`
}

func (m *MsgSubmitShareResponse) Reset()         { *m = MsgSubmitShareResponse{} }
func (m *MsgSubmitShareResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitShareResponse) ProtoMessage()    {}
func (*MsgSubmitShareResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_73caeafae94255fb, []int{3}
}
func (m *MsgSubmitShareResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitShareResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitShareResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitShareResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitShareResponse.Merge(m, src)
}
func (m *MsgSubmitShareResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitShareResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitShareResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitShareResponse proto.InternalMessageInfo

func (m *MsgSubmitShareResponse) GetMintedAmount() string {
	if m != nil {
		return m.MintedAmount
	}
	return ""
}

type MsgUnregisterDevice struct {
	// owner must match the device's currently-registered owner.
	Owner    string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	DeviceId string `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
}

func (m *MsgUnregisterDevice) Reset()         { *m = MsgUnregisterDevice{} }
func (m *MsgUnregisterDevice) String() string { return proto.CompactTextString(m) }
func (*MsgUnregisterDevice) ProtoMessage()    {}
func (*MsgUnregisterDevice) Descriptor() ([]byte, []int) {
	return fileDescriptor_73caeafae94255fb, []int{4}
}
func (m *MsgUnregisterDevice) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUnregisterDevice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUnregisterDevice.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUnregisterDevice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUnregisterDevice.Merge(m, src)
}
func (m *MsgUnregisterDevice) XXX_Size() int {
	return m.Size()
}
func (m *MsgUnregisterDevice) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUnregisterDevice.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUnregisterDevice proto.InternalMessageInfo

func (m *MsgUnregisterDevice) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *MsgUnregisterDevice) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

type MsgUnregisterDeviceResponse struct {
}

func (m *MsgUnregisterDeviceResponse) Reset()         { *m = MsgUnregisterDeviceResponse{} }
func (m *MsgUnregisterDeviceResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUnregisterDeviceResponse) ProtoMessage()    {}
func (*MsgUnregisterDeviceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_73caeafae94255fb, []int{5}
}
func (m *MsgUnregisterDeviceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUnregisterDeviceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUnregisterDeviceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUnregisterDeviceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUnregisterDeviceResponse.Merge(m, src)
}
func (m *MsgUnregisterDeviceResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUnregisterDeviceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUnregisterDeviceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUnregisterDeviceResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgRegisterDevice)(nil), "cosmos.evm.bandwidth.v1.MsgRegisterDevice")
	proto.RegisterType((*MsgRegisterDeviceResponse)(nil), "cosmos.evm.bandwidth.v1.MsgRegisterDeviceResponse")
	proto.RegisterType((*MsgSubmitShare)(nil), "cosmos.evm.bandwidth.v1.MsgSubmitShare")
	proto.RegisterType((*MsgSubmitShareResponse)(nil), "cosmos.evm.bandwidth.v1.MsgSubmitShareResponse")
	proto.RegisterType((*MsgUnregisterDevice)(nil), "cosmos.evm.bandwidth.v1.MsgUnregisterDevice")
	proto.RegisterType((*MsgUnregisterDeviceResponse)(nil), "cosmos.evm.bandwidth.v1.MsgUnregisterDeviceResponse")
}

func init() { proto.RegisterFile("cosmos/evm/bandwidth/v1/tx.proto", fileDescriptor_73caeafae94255fb) }

var fileDescriptor_73caeafae94255fb = []byte{
	// 550 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0x3f, 0x6f, 0xd3, 0x40,
	0x1c, 0xcd, 0xb5, 0x0d, 0x90, 0x5f, 0xff, 0x88, 0x9a, 0x08, 0x5c, 0x87, 0x9a, 0xc8, 0x08, 0x35,
	0x8a, 0xc0, 0x56, 0x03, 0x02, 0x11, 0x89, 0x21, 0x85, 0x05, 0xa1, 0x2c, 0x8e, 0x58, 0x58, 0x22,
	0xc7, 0x3e, 0x5d, 0x4e, 0xd4, 0x77, 0x91, 0xef, 0xe2, 0x36, 0x1b, 0x62, 0x64, 0xe2, 0x0b, 0xf0,
	0x1d, 0x32, 0x30, 0xf0, 0x11, 0x18, 0x2b, 0x26, 0x36, 0x50, 0x32, 0x64, 0xe3, 0x33, 0x20, 0xfb,
	0x92, 0x28, 0x4d, 0x48, 0x14, 0x86, 0x2e, 0x96, 0xef, 0xdd, 0xbb, 0x77, 0xbf, 0xf7, 0x7e, 0x3f,
	0x1b, 0x8a, 0x3e, 0x17, 0x21, 0x17, 0x0e, 0x8e, 0x43, 0xa7, 0xe5, 0xb1, 0xe0, 0x8c, 0x06, 0xb2,
	0xed, 0xc4, 0xc7, 0x8e, 0x3c, 0xb7, 0x3b, 0x11, 0x97, 0x5c, 0xbb, 0xa3, 0x18, 0x36, 0x8e, 0x43,
	0x7b, 0xca, 0xb0, 0xe3, 0x63, 0x63, 0xdf, 0x0b, 0x29, 0xe3, 0x4e, 0xfa, 0x54, 0x5c, 0x63, 0xcc,
	0x75, 0x42, 0x41, 0x12, 0x8d, 0x50, 0x90, 0xf1, 0xc6, 0x81, 0xda, 0x68, 0xa6, 0x2b, 0x67, 0xac,
	0xa8, 0xb6, 0xf2, 0x84, 0x13, 0xae, 0xf0, 0xe4, 0x4d, 0xa1, 0xd6, 0x37, 0x04, 0xfb, 0x75, 0x41,
	0x5c, 0x4c, 0xa8, 0x90, 0x38, 0x7a, 0x85, 0x63, 0xea, 0x63, 0xcd, 0x86, 0x2c, 0x3f, 0x63, 0x38,
	0xd2, 0x51, 0x11, 0x95, 0x72, 0x27, 0xfa, 0x8f, 0xaf, 0x8f, 0xf2, 0x63, 0xb1, 0x5a, 0x10, 0x44,
	0x58, 0x88, 0x86, 0x8c, 0x28, 0x23, 0xae, 0xa2, 0x69, 0x05, 0xc8, 0x05, 0xe9, 0xc9, 0x26, 0x0d,
	0xf4, 0x8d, 0xe4, 0x8c, 0x7b, 0x43, 0x01, 0xaf, 0x03, 0xed, 0x10, 0xa0, 0xd3, 0x6d, 0x9d, 0x52,
	0xbf, 0xf9, 0x1e, 0xf7, 0xf4, 0xcd, 0x22, 0x2a, 0xed, 0xb8, 0x39, 0x85, 0xbc, 0xc1, 0xbd, 0xea,
	0xb3, 0x8f, 0xa3, 0x7e, 0x59, 0xe9, 0x7c, 0x1a, 0xf5, 0xcb, 0xa5, 0x99, 0xa0, 0xce, 0x67, 0xa2,
	0x5a, 0x28, 0xd2, 0x2a, 0xc0, 0xc1, 0x02, 0xe8, 0x62, 0xd1, 0xe1, 0x4c, 0x60, 0xeb, 0x0f, 0x82,
	0xbd, 0xba, 0x20, 0x8d, 0x6e, 0x2b, 0xa4, 0xb2, 0xd1, 0xf6, 0x22, 0xac, 0x55, 0xe0, 0x7a, 0x84,
	0x4f, 0xbd, 0xde, 0x1a, 0xb6, 0x26, 0xc4, 0xd5, 0xc6, 0xee, 0xc1, 0xb6, 0x48, 0x94, 0x9b, 0x3e,
	0xef, 0x32, 0x99, 0x3a, 0xdb, 0x75, 0x21, 0x85, 0x5e, 0x26, 0x88, 0x96, 0x87, 0x2c, 0xe3, 0xcc,
	0xc7, 0xfa, 0x56, 0x11, 0x95, 0xb6, 0x5c, 0xb5, 0xd0, 0xee, 0x42, 0x4e, 0x50, 0xc2, 0x3c, 0xd9,
	0x8d, 0xb0, 0x9e, 0x55, 0x71, 0x4c, 0x81, 0xea, 0xd3, 0x24, 0x8e, 0xc9, 0xfd, 0x49, 0x20, 0x0f,
	0x96, 0x07, 0x32, 0xe3, 0xce, 0x7a, 0x01, 0xb7, 0x2f, 0x23, 0x93, 0x28, 0xb4, 0xfb, 0xb0, 0x1b,
	0x52, 0x26, 0x71, 0xd0, 0xf4, 0xc2, 0xb4, 0xd0, 0xd4, 0xbd, 0xbb, 0xa3, 0xc0, 0x5a, 0x8a, 0x59,
	0x5f, 0x10, 0xdc, 0xaa, 0x0b, 0xf2, 0x96, 0x45, 0x57, 0x37, 0x09, 0xd5, 0xe7, 0x97, 0x5b, 0x5d,
	0x5e, 0xee, 0x6c, 0xbe, 0x0e, 0xeb, 0x10, 0x0a, 0xff, 0x80, 0x27, 0x1e, 0x2b, 0xbf, 0x36, 0x60,
	0xb3, 0x2e, 0x88, 0xd6, 0x81, 0xbd, 0xb9, 0x51, 0x2e, 0xdb, 0x4b, 0xbe, 0x2b, 0x7b, 0x61, 0x78,
	0x8c, 0xca, 0xfa, 0xdc, 0x69, 0xba, 0x04, 0xb6, 0x67, 0x87, 0xec, 0x68, 0x95, 0xc4, 0x0c, 0xd1,
	0x70, 0xd6, 0x24, 0x4e, 0x2f, 0x8a, 0xe1, 0xe6, 0x42, 0x77, 0x1e, 0xae, 0x12, 0x99, 0x67, 0x1b,
	0x4f, 0xfe, 0x87, 0x3d, 0xb9, 0xd7, 0xc8, 0x7e, 0x18, 0xf5, 0xcb, 0xe8, 0xa4, 0xf6, 0x7d, 0x60,
	0xa2, 0x8b, 0x81, 0x89, 0x7e, 0x0f, 0x4c, 0xf4, 0x79, 0x68, 0x66, 0x2e, 0x86, 0x66, 0xe6, 0xe7,
	0xd0, 0xcc, 0xbc, 0x3b, 0x22, 0x54, 0xb6, 0xbb, 0x2d, 0xdb, 0xe7, 0xa1, 0xb3, 0xa4, 0xa3, 0xb2,
	0xd7, 0xc1, 0xa2, 0x75, 0x2d, 0xfd, 0xe5, 0x3c, 0xfe, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x51, 0xee,
	0x1a, 0x69, 0x0c, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// RegisterDevice registers a new ESP32 device, linking its public key to an
	// owner wallet. Only the owner needs to sign this transaction.
	RegisterDevice(ctx context.Context, in *MsgRegisterDevice, opts ...grpc.CallOption) (*MsgRegisterDeviceResponse, error)
	// SubmitShare relays a device-signed share submission. Anyone (e.g. a relay
	// server) can broadcast this transaction and pay its normal fees; the share
	// is only accepted if `signature` verifies against the registered device's
	// public key, so the relayer cannot forge shares.
	SubmitShare(ctx context.Context, in *MsgSubmitShare, opts ...grpc.CallOption) (*MsgSubmitShareResponse, error)
	// UnregisterDevice removes a device's on-chain registration. Only the
	// device's registered owner can unregister it. This does not affect the
	// physical device or any already-minted rewards; the device simply can no
	// longer submit shares (SubmitShare) until it is registered again.
	UnregisterDevice(ctx context.Context, in *MsgUnregisterDevice, opts ...grpc.CallOption) (*MsgUnregisterDeviceResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) RegisterDevice(ctx context.Context, in *MsgRegisterDevice, opts ...grpc.CallOption) (*MsgRegisterDeviceResponse, error) {
	out := new(MsgRegisterDeviceResponse)
	err := c.cc.Invoke(ctx, "/cosmos.evm.bandwidth.v1.Msg/RegisterDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SubmitShare(ctx context.Context, in *MsgSubmitShare, opts ...grpc.CallOption) (*MsgSubmitShareResponse, error) {
	out := new(MsgSubmitShareResponse)
	err := c.cc.Invoke(ctx, "/cosmos.evm.bandwidth.v1.Msg/SubmitShare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UnregisterDevice(ctx context.Context, in *MsgUnregisterDevice, opts ...grpc.CallOption) (*MsgUnregisterDeviceResponse, error) {
	out := new(MsgUnregisterDeviceResponse)
	err := c.cc.Invoke(ctx, "/cosmos.evm.bandwidth.v1.Msg/UnregisterDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// RegisterDevice registers a new ESP32 device, linking its public key to an
	// owner wallet. Only the owner needs to sign this transaction.
	RegisterDevice(context.Context, *MsgRegisterDevice) (*MsgRegisterDeviceResponse, error)
	// SubmitShare relays a device-signed share submission. Anyone (e.g. a relay
	// server) can broadcast this transaction and pay its normal fees; the share
	// is only accepted if `signature` verifies against the registered device's
	// public key, so the relayer cannot forge shares.
	SubmitShare(context.Context, *MsgSubmitShare) (*MsgSubmitShareResponse, error)
	// UnregisterDevice removes a device's on-chain registration. Only the
	// device's registered owner can unregister it. This does not affect the
	// physical device or any already-minted rewards; the device simply can no
	// longer submit shares (SubmitShare) until it is registered again.
	UnregisterDevice(context.Context, *MsgUnregisterDevice) (*MsgUnregisterDeviceResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) RegisterDevice(ctx context.Context, req *MsgRegisterDevice) (*MsgRegisterDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterDevice not implemented")
}
func (*UnimplementedMsgServer) SubmitShare(ctx context.Context, req *MsgSubmitShare) (*MsgSubmitShareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitShare not implemented")
}
func (*UnimplementedMsgServer) UnregisterDevice(ctx context.Context, req *MsgUnregisterDevice) (*MsgUnregisterDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnregisterDevice not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_RegisterDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterDevice)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.evm.bandwidth.v1.Msg/RegisterDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterDevice(ctx, req.(*MsgRegisterDevice))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SubmitShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitShare)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.evm.bandwidth.v1.Msg/SubmitShare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitShare(ctx, req.(*MsgSubmitShare))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UnregisterDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUnregisterDevice)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UnregisterDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.evm.bandwidth.v1.Msg/UnregisterDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UnregisterDevice(ctx, req.(*MsgUnregisterDevice))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cosmos.evm.bandwidth.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterDevice",
			Handler:    _Msg_RegisterDevice_Handler,
		},
		{
			MethodName: "SubmitShare",
			Handler:    _Msg_SubmitShare_Handler,
		},
		{
			MethodName: "UnregisterDevice",
			Handler:    _Msg_UnregisterDevice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cosmos/evm/bandwidth/v1/tx.proto",
}

func (m *MsgRegisterDevice) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterDevice) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterDevice) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DeviceSignature) > 0 {
		i -= len(m.DeviceSignature)
		copy(dAtA[i:], m.DeviceSignature)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DeviceSignature)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.PublicKey) > 0 {
		i -= len(m.PublicKey)
		copy(dAtA[i:], m.PublicKey)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PublicKey)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.DeviceId) > 0 {
		i -= len(m.DeviceId)
		copy(dAtA[i:], m.DeviceId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DeviceId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRegisterDeviceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterDeviceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterDeviceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSubmitShare) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitShare) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitShare) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Nonce != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Nonce))
		i--
		dAtA[i] = 0x20
	}
	if m.ShareCount != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ShareCount))
		i--
		dAtA[i] = 0x18
	}
	if len(m.DeviceId) > 0 {
		i -= len(m.DeviceId)
		copy(dAtA[i:], m.DeviceId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DeviceId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Relayer) > 0 {
		i -= len(m.Relayer)
		copy(dAtA[i:], m.Relayer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Relayer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubmitShareResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitShareResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitShareResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MintedAmount) > 0 {
		i -= len(m.MintedAmount)
		copy(dAtA[i:], m.MintedAmount)
		i = encodeVarintTx(dAtA, i, uint64(len(m.MintedAmount)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUnregisterDevice) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUnregisterDevice) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUnregisterDevice) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DeviceId) > 0 {
		i -= len(m.DeviceId)
		copy(dAtA[i:], m.DeviceId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DeviceId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUnregisterDeviceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUnregisterDeviceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUnregisterDeviceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgRegisterDevice) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.DeviceId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.PublicKey)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.DeviceSignature)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRegisterDeviceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSubmitShare) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Relayer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.DeviceId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.ShareCount != 0 {
		n += 1 + sovTx(uint64(m.ShareCount))
	}
	if m.Nonce != 0 {
		n += 1 + sovTx(uint64(m.Nonce))
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSubmitShareResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MintedAmount)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUnregisterDevice) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.DeviceId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUnregisterDeviceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgRegisterDevice) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterDevice: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterDevice: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeviceId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DeviceId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublicKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PublicKey = append(m.PublicKey[:0], dAtA[iNdEx:postIndex]...)
			if m.PublicKey == nil {
				m.PublicKey = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeviceSignature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DeviceSignature = append(m.DeviceSignature[:0], dAtA[iNdEx:postIndex]...)
			if m.DeviceSignature == nil {
				m.DeviceSignature = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterDeviceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterDeviceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterDeviceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitShare) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitShare: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitShare: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Relayer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Relayer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeviceId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DeviceId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShareCount", wireType)
			}
			m.ShareCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ShareCount |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nonce", wireType)
			}
			m.Nonce = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Nonce |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitShareResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitShareResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitShareResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MintedAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MintedAmount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUnregisterDevice) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUnregisterDevice: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUnregisterDevice: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeviceId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DeviceId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUnregisterDeviceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUnregisterDeviceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUnregisterDeviceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
